### ISSUE TITLE
Cannot Upload Images

### ISSUE THREAD

**Issue by aerostah** [seandowney/laravel-backpack-gallery-crud#12]
I am trying to use the gallery_table.blade field in a custom Backpack crud.  After getting past a few obstacles, i'm at the point where no errors served, however, i'm not seeing the repeatable inputs to upload images/captions.

This is happening in both GalleryCrudController.php and my own custom ListingCrudController.php

I've seen previous issues raised by other users regarding this same problem, you replied that we must create a folder, matching the name of the slug, to get the input fields to appear.  I am having no success with this approach.  I only see the field label Images.

1. Are we expected to create a folder before making a new gallery? 
2. Do you have any other suggestions for troubleshooting this?  

You've created such an important field type, it'd be a shame for it to not work.

Thank you.

**Comment by seandowney** [comment]
@aerostah unfortunately it's not as smooth a workflow as that.

The way it works for the Gallery crud is that:
* when you create the Gallery it also creates the folder in File Manager 
* next you must upload the images you want to that folder using File Manager
* then it's back to the Gallery CRUD where the images now appear in the list where you can enter the caption

Using the field outside the Gallery package you will have to do similar things to pass the data to the filed. 

I hope this helps.

**Comment by aerostah** [comment]
Thank you for clarifying this.  For streamlining this, do you think it would make sense to create a separate upload multiple files field before the gallery field, so the user can do everything in one place?

Basic instruction would be, upload your images, then, save the listing to insert captions, etc.

**Comment by seandowney** [comment]
Yes I think that would be ideal. I'm sure it's possible but I don't have the time to start into that at the moment. If you want to have a look that would be cool.

**Comment by seandowney** [comment]
I'll close this for now.
