### ISSUE TITLE
TypeError: CKEDITOR.style.addCustomHandler is not a function

### ISSUE THREAD

**Issue by acharyasarvesh** [seandowney/laravel-backpack-gallery-crud#2]
![admin_gallery_create](https://cloud.githubusercontent.com/assets/6910626/23623004/d8d699be-02c6-11e7-8b24-538b92418677.png)

**Comment by seandowney** [comment]
Could you give some more information about it please. The screenshot looks ok? 

⁣

**Comment by acharyasarvesh** [comment]
Hi Sean
As you can see in the screenshot there is no option to upload images and in console the error message displaying is "TypeError: CKEDITOR.style.addCustomHandler is not a function".

**Comment by grupaoem** [comment]
@acharyasarvesh Did you fix the problem?

**Comment by acharyasarvesh** [comment]
@grupaoem Nope. I used another option instead.

**Comment by seandowney** [comment]
The images are uploaded to a gallery folder with the slug name using elfinder.

The workflow needs to be improved, it was my first attempt. :-|
