### ISSUE TITLE
vendor:publish command not generating files

### ISSUE THREAD

**Issue by novocent** [seandowney/laravel-backpack-gallery-crud#3]
Using Laravel 5.4.15, the artisan vendor:publish command did not appear to generate the required files for me. Publishing completes, but does not throw any error.

**Comment by physio** [comment]
same error.

**Comment by seandowney** [comment]
Thanks both for reporting, I'll have a look this evening.

**Comment by seandowney** [comment]
@novocent @physio Sorry for the delay, this issue should be fixed now.

I suspect you needed "cviebrock/eloquent-sluggable" and "Cviebrock\EloquentSluggable\ServiceProvider::class," added to the config/app.php
