### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by phuongmt** [seandowney/laravel-backpack-gallery-crud#4]
Hi seandowney,
I already installed plugin but it is not work.
![image](https://cloud.githubusercontent.com/assets/3401962/26338137/facda378-3fa7-11e7-9fd2-7a916e991cab.png)

It only show label of gallery_table field.
I checked your code, it just show images have been added in database. Does not has add button to upload new image.
![image](https://cloud.githubusercontent.com/assets/3401962/26338165/2e60807a-3fa8-11e7-8548-85abc9799e3a.png)

**Comment by joaovcarvalho** [comment]
I am having the same issue here. Anyone can help ?

**Comment by seandowney** [comment]
@phuongmt @joaovcarvalho apologies for the incredibly late reply.

I will add this to the documentation but the galleries use the elfinder. You need to create a folder with the same name as the slug of your gallery under the `galleries` directory that you setup in step 4.

Then you upload your images there using elfinder.

Once this is done then they are available in the gallery admin.

It's not a great workflow, I am trying to improve that.

**Comment by seandowney** [comment]
I've added documentation to the readme now. I hope it helps though you are probably not using this now :-(
