### ISSUE TITLE
syntax error, unexpected 'image' (T_STRING), expecting ',' or ')' (View: ...resources\views\vendor\backpack\crud\fields\gallery_table.blade.php)

### ISSUE THREAD

**Issue by Dakaa** [seandowney/laravel-backpack-gallery-crud#9]
`syntax error, unexpected 'image' (T_STRING), expecting ',' or ')' (View: ...resources\views\vendor\backpack\crud\fields\gallery_table.blade.php)`

This happened when I tried to create a new gallery. Is this package compatible with the latest laravel backpack version?

**Comment by seandowney** [comment]
@dakaa

This PR should have fixed it. 
Are you still seeing the issue? 

https://github.com/seandowney/laravel-backpack-gallery-crud/pull/7

It might not be compatible with the latest version.

**Comment by Dakaa** [comment]
> @Dakaa
> 
> This PR should have fixed it.
> Are you still seeing the issue?
> 
> #7
> 
> It might not be compatible with the latest version.

Thanks Sean, your help is appreciated.

**Comment by Inigo-Pascall** [comment]
I have this issue as well. Latest Laravel 5.8, & latest Backpack.

**Comment by Inigo-Pascall** [comment]
OK, I've found the issue, which is line 54 on `gallery_table.blade.php`:

`<img src="{{ gallery_image_url($item['image_path'].'?w=50&h=50&fit=fill) }}" width="50" height="50"/>`

Should be

`<img src="{{ gallery_image_url($item['image_path'].'?w=50&h=50&fit=fill') }}" width="50" height="50"/>`
